feat: team projects
redkubes/otomi-core pull request #1132
Opened 2023-05-26 15:41 UTC by ferruhcihan

### Implements:
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/574

### Description:
This PR adds fields to the `values-schema.yaml` file for team projects feature.

### Changes Made:
Added `projects` and `project` fields to the `values-schema.yaml` file.

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2023-05-30 06:36 UTC, j-zimnowoda requested changes

2023-05-30 06:36 UTC, j-zimnowoda commented on values-schema.yaml
> +    description: Define location of code to project
Perhaps some better description, like:
```
A single project can represent application's build, workload and service.
```

2023-05-30 06:37 UTC, j-zimnowoda requested changes
Could you improve description ?

2023-06-01 09:10 UTC, j-zimnowoda approved these changes

2023-06-01 09:11 UTC, merged

2023-06-05 11:47 UTC, ElderMatt reviewed
looks good