fix: upgrade script for kube-prom stack
redkubes/otomi-core pull request #1173
Opened 2023-07-03 14:42 UTC by Ani1357

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2023-07-03 16:11 UTC, j-zimnowoda requested changes
Hi I like the usage of `2>/dev/null` to hide logs from checks.
Could merge your PR with main. There is slightly different approach for implementing logic, which I find more readable.

2023-07-04 14:52 UTC, j-zimnowoda requested changes
Perhaps you have forgotten to push last commit 😬

2023-07-06 09:01 UTC, Ani1357 commented
thats true, my bad 😅

2023-07-06 16:32 UTC, j-zimnowoda approved these changes

2023-07-06 16:37 UTC, merged