feat: tekton triggers
redkubes/otomi-core pull request #1276
Opened 2023-09-12 17:48 UTC by srodenhuis

This PR:

- adds Tekton trigger CRDs
- adds the option to use a triggertemplate instead of a pipelinerun to use a trigger to start the build
- adds all required RBAC to use triggers to the team-ns

2023-09-21 06:11 UTC, j-zimnowoda submitted a review, later dismissed

2023-09-21 06:30 UTC, j-zimnowoda reviewed
Still we need to test it

2023-09-25 10:11 UTC, j-zimnowoda requested changes
There is quite some work to be done here:
1. Bootstrap chart with `helm create tekton-triggers` and then modify it with you templates
2. Reiterate over RBAC and required permissions because current one are quite extensive.
3. Enrich the integrations tests `minimal-with-team.yaml` to accommodate build triggers with some example repo that is hosted at GitHub in redkubes org.

2023-09-25 10:11 UTC, j-zimnowoda commented on charts/tekton-triggers/templates/interceptors.yaml
> +    app.kubernetes.io/component: interceptors
please split this file to corresponding file names
e.g.: ConfigMap to configmap.yaml

2023-09-25 10:11 UTC, j-zimnowoda commented on charts/tekton-triggers/templates/interceptors.yaml
> +    app.kubernetes.io/name: core-interceptors
these labels should be referenced from the _helpers.yaml file

2023-09-25 10:11 UTC, j-zimnowoda commented on charts/tekton-triggers/templates/release.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Please split this file to smaller chunks

2023-09-25 10:35 UTC, srodenhuis commented on charts/team-ns/templates/builds/buildpack.yaml
> +                  storage: 1Gi
the shared data in the workspace is only used for the git clone, not for building images. When git is cloned, the build task uses this for building. The build is done in a container and then pushed. The size is not related to the size of the image that has been build.

2023-09-25 10:39 UTC, srodenhuis commented on charts/team-ns/templates/builds/buildpack.yaml
> +        serviceAccountName: sa-team-{{ $v.teamId }}
No. the sa here is the same as in the pipelinerun without a trigger. The `sa-team-{{ $v.teamId }}` has the required secrets needed to push images to harbor

2023-09-25 10:40 UTC, srodenhuis commented on charts/team-ns/templates/builds/docker.yaml
> +                  storage: 1Gi
See previous

2023-09-25 10:41 UTC, srodenhuis commented on charts/team-ns/templates/builds/buildpack.yaml
> +  name: gitea-triggerbinding-{{ .name }}
No. All build names are unique

2023-09-25 11:14 UTC, srodenhuis commented on charts/team-ns/templates/rbac.yaml
> +metadata:
not so extensive. only for specific resources

2023-09-25 11:34 UTC, j-zimnowoda commented on charts/team-ns/templates/builds/buildpack.yaml
> +                  storage: 1Gi
Ok, we found out that layers are stored in host (emptyDir)

2023-09-25 11:34 UTC, j-zimnowoda commented on charts/team-ns/templates/builds/buildpack.yaml
> +  name: gitea-triggerbinding-{{ .name }}
ok, it is responsibility of upper layer to ensure name uniqueness

2023-09-25 11:35 UTC, j-zimnowoda commented on charts/team-ns/templates/builds/buildpack.yaml
> +        serviceAccountName: sa-team-{{ $v.teamId }}
thanks

2023-09-25 11:47 UTC, j-zimnowoda approved these changes

2023-09-25 11:49 UTC, j-zimnowoda approved these changes

2023-09-25 14:46 UTC, merged