feat: keycloak upgrade
redkubes/otomi-core pull request #1280
Opened 2023-09-15 15:52 UTC by j-zimnowoda

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2023-09-21 09:07 UTC, j-zimnowoda commented
There is some comment about this branch. See: #1283

2023-09-25 11:11 UTC, ElderMatt commented
Where are the groups? I created 2 teams but they dont show up in keycloak, now I cannot assign users to a group.
![image](https://github.com/redkubes/otomi-core/assets/18527012/c44bea10-a2c2-4423-8fe8-ee05a59caa54)
![image](https://github.com/redkubes/otomi-core/assets/18527012/2f54062b-1f6b-4b85-9dd1-fea724d25e77)

2023-09-25 11:12 UTC, ElderMatt requested changes
At the moment Teams/groups are not automatically added in keycloak

2023-09-25 11:57 UTC, j-zimnowoda commented
> At the moment Teams/groups are not automatically added in keycloak

Perhaps the Otomi-tasks needs to be update to use compatible client.

2023-09-26 07:35 UTC, Ani1357 commented
From the screenshot I see you are checking the master realm in keycloak instead of otomi. Please change the realm in the top left dropdown box and check again.

2023-09-27 20:37 UTC, j-zimnowoda commented on values-changes.yaml
> +      - apps.keycloak.postgresqlPassword
also
`- apps.resources. postgresql`

2023-09-28 08:11 UTC, merged