fix: remove tempo link and tempo team app
redkubes/otomi-core pull request #1304
Opened 2023-09-29 13:43 UTC by srodenhuis

This PR removes the link from the Tempo app on the platform level and removes Tempo as a team app. When Tempo is enabled a datasource is added to Grafana. To see traces on the platform level, go to Grafana.
Teams can only see traces based on a traceId in the logs. There is no need to add Tempo as a team app

2023-10-02 11:08 UTC, j-zimnowoda approved these changes

2023-10-02 11:09 UTC, j-zimnowoda approved these changes

2023-10-02 11:10 UTC, j-zimnowoda requested changes

2023-10-02 11:10 UTC, j-zimnowoda commented on core.yaml
> -  - name: prometheus
why prometheus is removed?

2023-10-05 13:52 UTC, srodenhuis commented on core.yaml
> -  - name: prometheus
restored

2023-10-09 13:03 UTC, j-zimnowoda approved these changes

2023-10-09 13:04 UTC, merged