fix: readme for 1.0.0
redkubes/otomi-core pull request #1312
Opened 2023-10-05 19:11 UTC by srodenhuis

Update readme for 1.0.0

2023-10-05 20:27 UTC, j-zimnowoda commented on README.md
> +- [Let's Encrypt](https://letsencrypt.org/): A nonprofit Certificate Authority providing industry-recognized TLS certificates
This is not an application. How about 
```
cert-manager - bring your own wildcard certificate or request one from Let's Encrypt.
```
>

2023-10-05 20:29 UTC, j-zimnowoda requested changes
Looking good. Just one item to improve.

2023-10-06 06:40 UTC, srodenhuis commented on README.md
> +- [Let's Encrypt](https://letsencrypt.org/): A nonprofit Certificate Authority providing industry-recognized TLS certificates
check!

2023-10-06 11:21 UTC, j-zimnowoda approved these changes

2023-10-06 11:21 UTC, merged