Fc/feat/gitea otomi charts repo
redkubes/otomi-core pull request #1333
Opened 2023-10-18 08:16 UTC by ferruhcihan

### Implements:
https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/654

### Description:
This PR adds a feature to clone github otomi-charts repository and push to gitea. User can use the gitea charts repository for auto image updates.
Is paired with: https://github.com/redkubes/otomi-tasks/pull/88

### Changes Made:
Added cloneOtomiChartsInGitea function to call at the end of the apply command.

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2023-10-20 11:15 UTC, j-zimnowoda commented on src/cmd/commit.ts
> +  const otomiChartsUrl = 'https://github.com/redkubes/otomi-charts.git'
Let's make it configurable through env with the default to `https://github.com/redkubes/otomi-charts.git`

2023-10-20 12:00 UTC, ElderMatt reviewed
When Jeho's comment is resolved it looks good

2023-10-23 08:07 UTC, j-zimnowoda requested changes
There is just one comment to be covered

2023-10-23 09:46 UTC, j-zimnowoda commented on src/cmd/commit.ts
> +  const otomiChartsUrl = process.env.OTOMI_CHARTS_URL || 'https://github.com/redkubes/otomi-charts.git'
Ferruh, take a look at`src/validators.ts` file.
The env type and its default should be defined there.

2023-10-23 09:48 UTC, j-zimnowoda commented on .env.sample
> +OTOMI_CHARTS_URL=''
For dev purpose let's make it to `https://github.com/redkubes/otomi-charts`.
Then workload creation will be able to go through the all steps

2023-10-23 15:53 UTC, j-zimnowoda approved these changes

2023-10-23 15:53 UTC, merged