Fix/dashboards
redkubes/otomi-core pull request #1346
Opened 2023-10-24 13:47 UTC by staticvoid255

Fix datasource refs in dashboards, restore pod and deployment dashboards for admins, restore istio dashboards for teams.
This will allow drill-down to work, fixing redkubes/unassigned-issues#317 and also does some minor housekeeping

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2023-10-26 13:17 UTC, staticvoid255 commented
Sander pointed out another issue with the Velero dashboards, so I have converted back to draft

2023-10-30 10:28 UTC, j-zimnowoda commented on charts/grafana-dashboards/gatekeeper-teams/opa-gatekeeper-teams.json
> -        "uid": "P686CB814F81609FC"
successfully tested

2023-10-30 10:29 UTC, j-zimnowoda commented on charts/grafana-dashboards/istio-teams/service-dashboard.json
> -        "datasource": "-- Grafana --",
I see all the services BUT I should see only the one belonging to a team
<img width="1833" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/84ea19e9-937a-4677-896e-07de6a15b53f">

2023-10-30 10:31 UTC, j-zimnowoda commented on charts/grafana-dashboards/istio-teams/service-dashboard.json
> -        "datasource": "-- Grafana --",
<img width="1870" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/f50549a8-346e-490c-940f-3a68bd26d487">

2023-10-30 10:34 UTC, j-zimnowoda commented on charts/grafana-dashboards/trivy-teams/trivy-teams.json
> -  "gnetId": 16652,
I can't see this dashboard in a team
<img width="1889" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/d778810c-02e7-4842-a7a6-fb215beab0ca">

P.S.
Tracy has been enabled

2023-10-30 11:53 UTC, j-zimnowoda commented on charts/grafana-dashboards/k8s-admin/compute-cluster.json
> +            "linkUrl": "/d/a87fb0d919ec0ea5f6543124e16c42a5/k8s-resources-namespace?var-datasource=$datasource&var-cluster=$cluster&var-namespace=$__cell_1",
successfully tested 
![Uploading image.png…]()

2023-10-30 11:54 UTC, j-zimnowoda commented on charts/grafana-dashboards/k8s-admin/compute-deployment.json
> +{
successfully tested 
<img width="923" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/0427d02e-e976-4c46-9051-6b73c4a8a253">

2023-10-30 11:54 UTC, j-zimnowoda commented on charts/grafana-dashboards/k8s-admin/compute-ns.json
> +            "linkUrl": "/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?var-datasource=$datasource&var-cluster=$cluster&var-namespace=$namespace&var-workload=$__c
successfully tested 

<img width="933" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/0c47acee-062f-4bed-a87f-cb053b6ca8d1">

2023-10-30 11:55 UTC, j-zimnowoda commented on charts/grafana-dashboards/k8s-admin/compute-pods.json
> +{
successfully tested 
<img width="926" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/3ca60056-77ff-4cfe-9d91-f4c05ecf3b25">

2023-10-30 11:57 UTC, j-zimnowoda commented on charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
> -    {{`{"annotations":{"list":[]},"editable":true,"gnetId":null,"graphTooltip":0,"hideControls":false,"links":[],"refresh":"10s","rows":[{"collapse":false,"height":"100px","panels":[{"aliasColors":{}
successfully tested 
<img width="940" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/31e1f086-eefa-44a1-a516-e4542a9df617">

2023-10-30 12:00 UTC, j-zimnowoda commented on charts/grafana-dashboards/gatekeeper-teams/opa-gatekeeper-teams.json
> -        "uid": "P686CB814F81609FC"
<img width="945" alt="image" src="https://github.com/redkubes/otomi-core/assets/17126497/57d56401-11e9-4f26-b2dd-3c6dc8794b57">

2023-10-30 12:04 UTC, j-zimnowoda requested changes
Thanks for fixing the integration of Grafana Dashboards.
I checked all of them and provided some screenshots.
For this PR there are two things that need to changed:
1. Istio-team dashboards are not very helpful for a regular user and they do not limit the scope therefor I propose to not add them to team grafana
2. I cant's see Trivy dashboard, could you double check?

2023-10-31 08:30 UTC, j-zimnowoda approved these changes

2023-10-31 08:31 UTC, j-zimnowoda commented on charts/grafana-dashboards/istio-teams/service-dashboard.json
> -        "datasource": "-- Grafana --",
istio dashboard has been removed for teams

2023-10-31 08:31 UTC, merged