feat: mvp kyverno policies
redkubes/otomi-core pull request #1462
Opened 2024-01-10 15:09 UTC by srodenhuis

This MVP includes:

- adding Kyverno as a core app with 2 deployment profiles (DevTest and Prod)
- offer 5 policy profiles with (to start with) 25 policies
- policies are per team
- teams can customize policies, deactivate them or change the default action (enforce, audit)
- admins can block teams from changing policies

2024-04-16 14:29 UTC, merll commented on charts/team-ns/templates/policies/best-practice/disallow-latest-tag.yaml
> +          - image: "!*:latest"
Is the exemption using the label `policy.otomi.io/ignore` also considered? We currently use a `latest` tag image on buildpacks for example.

2024-04-17 08:22 UTC, CasLubbers requested changes
Some things I found which can be removed I think:
- The file `bin/build-gatekeeper-artifacts.sh` can also be removed right?
- In the README.md line 133 `OPA/Gatekeeper...` can be removed right?
- The policies directory can also be removed right? If so the project structure in docs/development.md should be adjusted corectly.
- The checkPolicies command in the Otomi CLI can also be removed right? This requires changes in `index.ts`, `binzx/README.md`, `check-policies.ts`, `tests.ts`
- The file docs/policies.md should be updated or removed right?
- In the file src/cmd/destroy.ts on line 105 `gatekeeper.sh` can be removed right?
- In the file src/cmd/test.ts on line 21 `  if (!values?.apps.gatekeeper!.disableValidatingWebhook) await checkPolicies()` can be removed right?
- In the file tests/integration/upgrade.yaml on line 18 `gatekeeper` can be removed right?

2024-04-17 08:37 UTC, CasLubbers commented
One more question, maybe I cannot find it because the PR is so big. But what are the default policies we set for the team-admin namespace?

2024-04-17 09:30 UTC, merll commented
I have attempted but failed to deploy this branch. Some pods fail to start:

kyverno/kyverno-admission-controller
```
2024-04-17T08:13:09Z    ERROR    klog    cache/reflector.go:147    k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v2alpha1.GlobalContextEntry: failed to list *v2alpha1.GlobalContextEntry: the server could not find the requested resource (get globalcontextentries.kyverno.io)
2024-04-17T08:13:31Z    INFO    klog    cache/reflector.go:539    k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v2alpha1.GlobalContextEntry: the server could not find the requested resource (get globalcontextentries.kyverno.io)
```

kyverno/kyverno-cleanup-controller
```
2024-04-17T08:11:43Z    ERROR    setup    cleanup-controller/main.go:124    sanity checks failed    {"error": "failed to check CRD cleanuppolicies.kyverno.io is installed: customresourcedefinitions.apiextensions.k8s.io \"cleanuppolicies.kyverno.io\" is forbidden: User \"system:serviceaccount:kyverno:kyverno-cleanup-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope; failed to check CRD clustercleanuppolicies.kyverno.io is installed: customresourcedefinitions.apiextensions.k8s.io \"clustercleanuppolicies.kyverno.io\" is forbidden: User \"system:serviceaccount:kyverno:kyverno-cleanup-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope", "errorCauses": [{"error": "failed to check CRD cleanuppolicies.kyverno.io is installed: customresourcedefinitions.apiextensions.k8s.io \"cleanuppolicies.kyverno.io\" is forbidden: User \"system:serviceaccount:kyverno:kyverno-cleanup-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope"}, {"error": "failed to check CRD clustercleanuppolicies.kyverno.io is installed: customresourcedefinitions.apiextensions.k8s.io \"clustercleanuppolicies.kyverno.io\" is forbidden: User \"system:serviceaccount:kyverno:kyverno-cleanup-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope"}]}
```

Any ideas?

2024-04-26 09:22 UTC, j-zimnowoda commented on values-schema.yaml
> +          mode:
Is mode solely for setting HA ? 
If so, could you rename it to ha, with type boolean?

2024-04-26 09:28 UTC, j-zimnowoda requested changes
The previous implementation gave us better control over integrated apps.
This one validates team resources against policies only.
Although, I see a lot of benefits in terms of reporting, I do not understand why did you abandon the policy checks for platform. Could you elaborate on that?

2024-06-21 09:16 UTC, j-zimnowoda approved these changes

2024-06-21 09:19 UTC, j-zimnowoda commented
> Some things I found which can be removed I think:
> 
> * The file `bin/build-gatekeeper-artifacts.sh` can also be removed right?
> * In the README.md line 133 `OPA/Gatekeeper...` can be removed right?
> * The policies directory can also be removed right? If so the project structure in docs/development.md should be adjusted corectly.
> * The checkPolicies command in the Otomi CLI can also be removed right? This requires changes in `index.ts`, `binzx/README.md`, `check-policies.ts`, `tests.ts`
> * The file docs/policies.md should be updated or removed right?
> * In the file src/cmd/destroy.ts on line 105 `gatekeeper.sh` can be removed right?
> * In the file src/cmd/test.ts on line 21 `  if (!values?.apps.gatekeeper!.disableValidatingWebhook) await checkPolicies()` can be removed right?
> * In the file tests/integration/upgrade.yaml on line 18 `gatekeeper` can be removed right?

Good points! We are going to perform further refactoring after this PR I merged.

2024-06-21 09:24 UTC, merged