Task #169: update GitHub templates
redkubes/otomi-core pull request #183
Opened 2020-10-27 07:29 UTC by martijncalker

Update the existing GitHub templates

2020-11-09 08:27 UTC, j-zimnowoda requested changes
Nice, I have only one remark. Please decide what is the best.

2020-11-09 08:27 UTC, j-zimnowoda commented on .github/ISSUE_TEMPLATE/feature_request.md
> +If applicable, add any other context about the problem here.
Aren't first four items part of commit message?

feat: add new feature
BREAKING CHANGE: this is breaking change

OR

fix: change sth
BREAKING CHANGE: this is breaking change

2020-11-09 08:27 UTC, j-zimnowoda commented on .github/ISSUE_TEMPLATE/feature_request.md
> -**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
Not needed. 
The problem section is described below:
> Briefly describe the feature you want to see added to Otomi, preferably in the form of a user-story (e.g. "As a [persona],

2020-11-12 15:18 UTC, Morriz commented
closing as this is mostly done via direct template edits

2020-11-12 15:18 UTC, closed without merging