feat: otomi branding for Keycloak (PoC)
redkubes/otomi-core pull request #193
Opened 2020-10-29 14:28 UTC by j-zimnowoda

It used to be an open PR and for some reason we lost it, so I am opening it again.

2020-10-29 14:29 UTC, j-zimnowoda commented on values/keycloak/keycloak.gotmpl
> +      image: "cdrocker/keycloak-otomi-branding:0.1.1"
need to be pulled from our repo

2020-10-29 21:29 UTC, Morriz commented
It's not much. Just 2 lines loading somebody else's theme

2020-11-11 13:13 UTC, Morriz requested changes

2020-11-11 13:13 UTC, Morriz commented on values/keycloak/keycloak.gotmpl
> +      image: "cdrocker/keycloak-otomi-branding:0.1.1"
cdrocker?

I thought we would put it in the `otomi/console` image

2020-11-11 13:13 UTC, Morriz commented on values/keycloak/keycloak.gotmpl
> +  extraVolumes: |
why are these pipes at the end?

2020-11-11 13:13 UTC, Morriz commented on values/keycloak/keycloak.gotmpl
> +  extraVolumeMounts: |
again, what's with that pipe?

2020-11-11 13:27 UTC, Morriz commented
@j-zimnowoda can I close this? I see another PR open for this

2020-11-11 13:34 UTC, j-zimnowoda commented
> @j-zimnowoda can I close this? I see another PR open for this

@Morriz I am working on this PR

2020-11-11 14:01 UTC, Morriz commented
of course ;p

2020-11-11 15:37 UTC, Morriz requested changes
please remove those redundant pipes

2020-11-12 03:12 UTC, Morriz approved these changes

2020-11-12 03:14 UTC, merged

2020-11-12 10:15 UTC, j-zimnowoda commented
> of course ;p
> 
> still interested to know why those pipes were put there ;)

@Morriz I also did not like those pipes. Bleeee
But after removing them helm could template it anymore.
It is because they expected extraInitcontainer to be raw string which they can template