Requirements setting istio telemetry rework
redkubes/otomi-core pull request #262
Opened 2020-12-23 08:22 UTC by svatwork

Issue: #164 
Task: Kiali operator added and configured

Apologies for being naive. Here, I have a basic configuration of Kiali Operator, but that's of course not sufficient. But I don't know what is under the definition of done for this story (or for any story adding new components), is it a basic configuration like this or are there any special requirements for integrating it?

2020-12-23 16:03 UTC, Morriz requested changes
seems like a work in progress

2020-12-23 16:03 UTC, Morriz commented on charts/istio-operator/Chart.yaml
> +  - https://github.com/istio/istio/operator
this is actually not the correct location as that is deprecated

2020-12-23 16:03 UTC, Morriz commented on charts/istio-operator/Chart.yaml
> +version: 1.9-dev
can we target stable? so 1.8 probably

2020-12-24 07:24 UTC, svatwork commented
> seems like a work in progress

Definitely, but I really wanted to know if I'm heading in the right direction. Would you please take a look at the requirements I made and tell me if I'm in the right direction? @Morriz

2021-01-04 16:26 UTC, j-zimnowoda commented
@svatwork making things clear is not naive IMO.
Thanks for making it more precise. Just maybe it is better to elaborate an issue itself.

For the code indeed work in progress. I guess you need some artefacts so Kiali operator knows what to do.

2021-01-05 08:11 UTC, closed without merging