Issue 380 - Adding AWS env vars to drun and vault operator
redkubes/otomi-core pull request #415
Opened 2021-04-23 08:30 UTC by mojtabaimani

Issue 380 - Adding AWS env vars to drun and vault operator

2021-04-26 08:31 UTC, Morriz requested changes
I see issues this PR because @j-zimnowoda did not properly support AWS KMS with SOPS (see https://github.com/mozilla/sops#kms-aws-profiles):
- `~/.aws/credentials` is not mounted in otomi drun for SOPS
- `SOPS_KMS_ARN` needs to be injected into drun

So the context of this work item needs to be known in order to get the expected outcome, which is that SOPS as well as Vault Operator can use the 3 cloud KMSes we support: 
- AWS KMS
- GCP KMS
- Azure Vault

The other integration point is the Drone chart, which is passing the same environment variables. Please look in the `values/drone.gotmpl` file to see. I now see that he also forgot to rewrite those params there as well, as those should now be coming from the `kms:` prop.

2021-04-26 08:31 UTC, Morriz commented on values/vault-operator/vault-operator-raw.gotmpl
> +          value: {{ $kms.awskms.region }}
please rewrite like this
```
{{- with $kms.awskms }}
  ...
  value: {{- .region }}
  ...
{{- end }}
```

2021-04-28 08:34 UTC, Morriz requested changes

2021-04-28 08:34 UTC, Morriz commented on values/drone/drone.gotmpl
> +    {{- with $kms.azurekeyvault }}
```suggestion
    {{- with ($kms | get "azurekeyvault" nil) }}
```

2021-04-28 08:34 UTC, Morriz commented on values/drone/drone.gotmpl
> +    {{- if hasKey $kms "azurekeyvault" }}
```suggestion
```

2021-04-28 09:20 UTC, j-zimnowoda requested changes
Thanks for enhancing settings for platform secrets.
Could you tell us, how did you test it?
So far a minor change that need to be applied in many places.

2021-04-28 11:22 UTC, Morriz commented
It starts to annoy me to see "Thank you" all the time for every little thing that is part of the work we do, and we get salaries for. I would not formalize this but instead keep it special for when somebody goes _beyond_ the expected.

But maybe that is me being allergic to every form of communication that loses meaning or impact over time.

Just wanted to share that.

2021-04-28 11:25 UTC, j-zimnowoda commented
> It starts to annoy me to see "Thank you" all the time for every little thing that is part of the work we do, and we get salaries for. I would not formalize this but instead keep it special for when somebody goes _beyond_ the expected.
> 
> But maybe that is me being allergic to every form of communication that loses meaning or impact over time.
> 
> Just wanted to share that.

I am afraid that it is your allergy and is not relevant to the content go the PR. No value added, no comment please.

2021-04-28 13:47 UTC, mojtabaimani commented on values/drone/drone.gotmpl
>      AZURE_ENVIRONMENT: "AZUREPUBLICCLOUD"
I am not sure about this. I just copied it from the current code.

2021-04-28 13:49 UTC, mojtabaimani commented on values/drone/drone.gotmpl
> +    GCLOUD_SERVICE_KEY: '{{ .kmsAccount }}'
I am not sure about this.

2021-04-29 05:23 UTC, svatwork approved these changes

2021-05-04 08:43 UTC, j-zimnowoda commented
please, merge with master

2021-05-07 02:13 UTC, merged