fix: in azureMonitor you need to provide either both of dlientId and …
redkubes/otomi-core pull request #422
Opened 2021-05-07 11:58 UTC by mojtabaimani

In value-schema, in azureMonitor you need to provide either both of dlientId and clientSecret together or non of them.

2021-05-07 12:33 UTC, j-zimnowoda requested changes
It is conform with json schema bit may not be with OAS 3.0
Also Please ensure that this can be rendered by https://rjsf-team.github.io/react-jsonschema-form/

2021-05-07 12:36 UTC, j-zimnowoda requested changes
Please ensure that this schema can be renderd as react form: https://rjsf-team.github.io/react-jsonschema-form/

Also check if 'dependencies' are conform with OAS 3.0

2021-05-09 21:38 UTC, Morriz requested changes

2021-05-09 21:38 UTC, Morriz commented on values-schema.yaml
> +        type: string
where is `tenantId`? How did that get lost @j-zimnowoda (I am asking you first after the single-repo refactor)? This was coming from the `azure.tenantId` prop. Where did the root `azure` prop go? And how was the refactoring done of the templates that relied on those?

2021-05-10 16:59 UTC, Morriz approved these changes

2021-05-10 17:03 UTC, merged