fix: removing empty keys from value skeleton
redkubes/otomi-core pull request #504
Opened 2021-08-04 18:42 UTC by mojtabaimani

Empty keys in value skeleton makes validation problem after merging with otomi chart values if user doesn't provide values for those empty keys.

2021-08-04 19:24 UTC, Dunky13 approved these changes
Lgtm

2021-08-05 07:38 UTC, j-zimnowoda requested changes

2021-08-05 07:38 UTC, j-zimnowoda commented on values/otomi-api/otomi-api.gotmpl
> +  CLUSTER_NAME: {{ $c | get "apiName" "api" }}
The otomi-api does not use CLUSTER_NAME anymore

2021-08-05 07:38 UTC, j-zimnowoda commented on values/otomi-api/otomi-api.gotmpl
>    CLUSTER_ID: {{ printf "%s/%s" $c.provider $c.name }}
The otomi-api does not use CLUSTER_ID anymore

2021-08-05 07:39 UTC, j-zimnowoda commented on values/otomi-api/otomi-api.gotmpl
>    CLUSTER_APISERVER: {{ $c.apiServer }}
ditto

2021-08-05 07:55 UTC, j-zimnowoda approved these changes

2021-08-05 08:12 UTC, merged