fix: create symbolic link on request to server
redkubes/otomi-core pull request #564
Opened 2021-08-31 19:50 UTC by j-zimnowoda

fixes #256

2021-08-31 19:57 UTC, Morriz requested changes
Hope this fixes it. Minor remarks related to dev principles. Like, don't defend against errors (those must surface and be fixed)

2021-08-31 19:57 UTC, Morriz commented on src/server/index.ts
> +  if (!existsSync(repoPath)) throw new Error(`The git repository does not exist at ${repoPath} path`)
This is never the case as we designed it to be there. No need for defending, and expecting it to "may be" different.

2021-08-31 19:57 UTC, Morriz commented on src/server/index.ts
> +  if (!existsSync(envPath)) symlinkSync(repoPath, envPath)
Don't do if here. It _must_ break if its not there.

2021-09-01 07:25 UTC, j-zimnowoda commented
It is not defending but postponed check.

2021-09-01 07:31 UTC, Dunky13 commented
Could it be that the server is started before a symlink is created?
https://github.com/redkubes/otomi-core/pull/564/files#diff-e4e7a68d82cdfba4e7dab9a32a8f55f3806ffa0cf33f1b8ab64b42941cf68888L61-L63

2021-09-01 08:53 UTC, Morriz approved these changes

2021-09-01 08:53 UTC, Morriz commented
great...tnx

2021-09-01 08:54 UTC, Morriz approved these changes

2021-09-01 08:56 UTC, Dunky13 commented
1 more change coming - to use ENV_DIR

2021-09-01 09:04 UTC, Dunky13 approved these changes

2021-09-01 09:10 UTC, merged