fix: node affinity match now excluding daemonsets
redkubes/otomi-core pull request #847
Opened 2022-07-21 14:53 UTC by Morriz

Daemonsets should not follow node affinity as those are mostly exporters.

## Checklist

- [x] Docs have been added to draw attention to template specifics (see TODO)

2022-07-21 16:20 UTC, Morriz commented
Note that this can only be tested by (removing and re)creating the top level resource responsible for creating pods: StatefulSet, CronJob, Job, Deployment, ReplicaSet (Pod not supported as immutable).

2022-07-25 07:03 UTC, j-zimnowoda commented on charts/gatekeeper-artifacts/templates/mutations.yaml
> +kind: Assign
CronJobs could also be added to the list

2022-07-25 13:58 UTC, j-zimnowoda requested changes
> Note that any empty/undefined match criteria are inclusive: they match any object.
https://open-policy-agent.github.io/gatekeeper/website/docs/mutation/

It means that ` set-team-node-affinity` mutation webhook  will apply to any Pod (also from core apps).

I will fix it in upcoming days

2022-07-26 07:37 UTC, j-zimnowoda approved these changes

2022-07-26 12:13 UTC, merged