feat: New loki multi-tenancy and promtail upgrade
redkubes/otomi-core pull request #910
Opened 2022-09-22 09:17 UTC by srodenhuis

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ x ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ x ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2022-09-22 11:11 UTC, j-zimnowoda requested changes

2022-09-22 11:11 UTC, j-zimnowoda commented on values/loki-teams/auth-config.gotmpl
> +users:
Files from values/loki-teams/ does not seem to be used

2022-09-22 12:14 UTC, j-zimnowoda approved these changes

2022-09-22 12:15 UTC, merged

2022-09-26 11:23 UTC, Morriz commented
Nice work guys