feat: Thanos and Minio with updated Velero config
redkubes/otomi-core pull request #937
Opened 2022-11-08 18:28 UTC by srodenhuis

This PR brings:

- Thanos and Minio in an out-of-the-box remote write setup
- Configure Prometheus for remote write
- Install Minio with provisioning (creating buckets and policies for all Otomi apps to consume object storage
- Splitting up cloud and storage provider for Velero to support using in-cluster Minio on other clouds

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ x ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ x ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2022-11-10 14:14 UTC, staticvoid255 commented
Hi Sander - I noticed that if you try to install Minio and Thanos at the same time, that Core will try to install Thanos first. This then causes the Drone pipeline to hang as Thanos is stuck in error trying to reach a Minio instance that doesn't yet exist.
<img width="1673" alt="Screenshot 2022-11-10 at 15 13 16" src="https://user-images.githubusercontent.com/59235486/201114485-cd5baa86-8ec7-4124-ab82-bcd49df2166b.png">

2022-11-11 10:42 UTC, Morriz commented
> Hi Sander - I noticed that if you try to install Minio and Thanos at the same time, that Core will try to install Thanos first. This then causes the Drone pipeline to hang as Thanos is stuck in error trying to reach a Minio instance that doesn't yet exist.
> <img alt="Screenshot 2022-11-10 at 15 13 16" width="1673" src="https://user-images.githubusercontent.com/59235486/201114485-cd5baa86-8ec7-4124-ab82-bcd49df2166b.png">

Any app that has a dependency on another service should wait for that service in a pre-install job. Easiest way to do that is to add a `needs:` dependency to the helmfile release by deploying another `wait-for` chart. Both releases need to be in the same helmfile. Example:
```yaml
  - name: thanos
    namespace: thanos
    needs: [maintenance/wait-for-minio]
    ...
  - name: wait-for-minio
    installed: {{ $a | get "minio.enabled" }}
    <<: *wait
    values:
      - url: {{ http://minio.minio }}
        host: minio.{{ $v.cluster | get "domainSuffix" nil }}
        tasksVersion: {{ $v.versions.tasks }}
        {{- if $v._derived.untrustedCA }}
        customCa: |
          {{- $v._derived.caCert | nindent 10 }}
        {{- end }}
        runPolicy: OnSpecChange    

```

2022-11-28 15:24 UTC, j-zimnowoda commented on helmfile.d/snippets/defaults.yaml
> +              retentionResolutionRaw: 30d
> As a rule of thumb retention for each downsampling level should be the same, and should be greater than the maximum date range (10 days for 5m to 1h downsampling).
https://thanos.io/tip/components/compact.md/#-downsampling-note-about-resolution-and-retention-

Could you explain why do you chose `retentionResolution1h: 10y`

2022-11-28 15:26 UTC, j-zimnowoda commented on helmfile.d/snippets/defaults.yaml
> +                size: 8Gi
> The compactor needs local disk space to store intermediate data for its processing as well as bucket state cache. Generally, for medium sized bucket about 100GB should be enough to keep working as the compacted time ranges grow over time.
https://thanos.io/tip/components/compact.md/#disk

8 GB does not seem to be a good default for compactor

2022-11-28 15:47 UTC, j-zimnowoda requested changes
So far few comments. Overall way too many changes in one PR.

2022-11-28 16:02 UTC, j-zimnowoda commented on values/minio/minio.gotmpl
> +extraVolumeMounts:
Could you add a comment in the code explaining why the same cert needs to be mounted twice?

2022-11-28 16:03 UTC, j-zimnowoda commented on values/minio/minio.gotmpl
> +{{- $vl:= $v.apps.minio }}
I believe this variable should be called `$m`

2022-11-28 18:02 UTC, closed without merging

2022-11-28 18:02 UTC, srodenhuis commented
Will be split up into 4 separate PRs