Feat/harbor backup
redkubes/otomi-core pull request #952
Opened 2022-11-22 15:34 UTC by srodenhuis

This PR brings:

- Backup the Harbor registry DB (using pg_dump) and store the backup in a Minio bucket
- A generic backup script that can be used in other jobs to create backups of postgres dbs and store the backup in a Minio bucket

This feature is now separated from the Harbor upgrade PR.

## Checklist

- [ ] Create new tools image
- [ ] Test backup

2022-11-29 07:36 UTC, j-zimnowoda commented on tools/Dockerfile
> +  postgresql-client \
Would it be possible to use `bitnami/postgresql` that contains all required tooling?

2022-11-29 08:28 UTC, j-zimnowoda commented on tools/Dockerfile
> +  postgresql-client \
Ah I see it is noot that easy as the aws CLI is also needed

2022-12-01 07:02 UTC, j-zimnowoda commented on helmfile.d/helmfile-99.post.yaml
> +    installed: {{ $a | get "harbor.backup.enabled" }}
I believe it should be:
```
installed: {{ and ($a.harbor.enabled) ($a | get "harbor.backup.enabled"  false) }}
```

You could also add the `harbor.backup.enabled` to the `defaults.yaml` file then you do not need to use `get`

2022-12-01 07:08 UTC, j-zimnowoda commented on values/harbor/harbor.gotmpl
> -harborAdminPassword: {{ $h | get "adminPassword" $v.otomi.adminPassword }}
I remember that you mentioned that there was an issue with logic here causing harbor db password being taken from the Helm chart. Still, I am wondering if this change can have any side effects on existing deployments. If so then we need to include it in the release notes.

2022-12-01 07:08 UTC, j-zimnowoda commented on values/harbor/harbor.gotmpl
> +  password: {{ $v.otomi.adminPassword }}
same as above

2022-12-01 07:12 UTC, j-zimnowoda requested changes

2022-12-01 07:12 UTC, j-zimnowoda commented on values/jobs/scripts/backup-db.sh
> +pg_dump -O -Fc --no-owner | aws --endpoint-url $ENDPOINT s3 cp - s3://$BUCKET/$POSTFIX/backup_$(date +%Y%m%d%H%M%S%N).dump
Could you rephrase the echo message, so it includes the filename of the backup?

2022-12-01 12:07 UTC, Morriz requested changes
Looking good. Thanks for moving it to our values/jobs.

Minor remark left

2022-12-01 13:55 UTC, j-zimnowoda commented on tools/Dockerfile
> -  awscli \
in line 38 the was cli is already installed

2022-12-01 15:49 UTC, srodenhuis commented on values/harbor/harbor.gotmpl
> +  password: {{ $v.otomi.adminPassword }}
Indeed. we'll fix it

2022-12-08 08:36 UTC, staticvoid255 commented
Am I correct in the assumptions that this is dependent on #945?

2022-12-13 10:39 UTC, j-zimnowoda approved these changes

2022-12-13 10:42 UTC, merged