fix: get files for encryption / decryption
redkubes/otomi-core pull request #976
Opened 2022-12-07 16:51 UTC by j-zimnowoda

fixes #975

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2022-12-07 17:09 UTC, Morriz requested changes
I fail to see how adding this unneeded stuff makes things better. I thought we were gonna fix a bug but this is adding unneeded and less readable / maintainable code. Can we keep it the way it was and just inject envDir where needed?

2022-12-07 17:09 UTC, Morriz commented on src/common/crypt.ts
> +  let filteredFiles: Array<string> = []
I don't see the point of this as sops already works this way. Before it was fine, so why try to suddenly emulate sops behaviour? Am I missing something?

2022-12-08 06:43 UTC, j-zimnowoda commented
@Morriz please ready first my findings in the issue https://github.com/redkubes/otomi-core/issues/975

2022-12-08 08:05 UTC, Morriz commented
I still think that writing an empty secrets file (without .dec) would be sufficient for the encrypt step to pick up. But I am not convinced that sops does not pick up a .dec file without the other file. Please demo that is the case first.

2022-12-08 11:15 UTC, closed without merging

2022-12-08 11:17 UTC, j-zimnowoda commented
I was able to reproduce it and that should be enough to to convince you.